"""CXA-FL-EGERIAMCP-01: characterization tests for ``reconcile`` (CCN 108).

``reconcile`` weaves the 34 harvest layers' independently-catalogued assets into
one graph via ~15 deterministic pattern matchers (see ``PATTERNS``), each
creating labelled ``DataFlow`` edges through the shared ``link()`` closure, plus
a confidentiality-propagation pass that is NOT gated through ``link()``.

These tests pin the CURRENT behaviour of the unmodified ``main``-branch
function — including its bugs — against a no-network fake Egeria client
(``FakeReconcileApi``). The fixture (``_build_catalog``) is a small but
deliberately cross-linked asset graph designed to exercise every one of the 15
patterns at least once (a positive AND, where cheap, a negative/no-match case),
plus THREE call sites that share the literal core name ``"shared1"`` across
Node/DataStore/Service/Route — this collision is what reveals BUG-1 and BUG-2
below (see the ``test_bug_*`` tests and the lane report).

Do not edit this file in commit 2 (the refactor commit) — it must stay
byte-identical; that is the two-commit discipline's proof that behaviour did
not change under the extract-method refactor.
"""

from __future__ import annotations

import json as _json

from egeria_mcp.reconcile import reconcile


def _asset(guid: str, qn: str, **extra) -> dict:
    d = {"guid": guid, "qualifiedName": qn}
    d.update(extra)
    return d


def _build_catalog() -> dict[str, list[dict]]:
    """Catalog keyed by the literal search-string term ``_paginated_search``
    is called with (one term per prefix in ``_PREFIXES``, plus ``"Term::"``
    for the semantic-assignment pattern's direct glossary lookup).
    """
    return {
        "Node::": [_asset("n1", "Node::web1"), _asset("n3", "Node::shared1")],
        "Host::": [_asset("n2", "Host::dbhost")],
        "DataStore::": [
            _asset(
                "s1",
                "DataStore::kafka",
                additionalProperties={"hostNode": "web1"},
                displayName="Kafka Cluster",
            ),
            _asset("s2", "DataStore::shared1"),
            _asset(
                "s3", "DataStore::files", additionalProperties={"hostNode": "dbhost"}
            ),
        ],
        "Dataset::": [
            _asset("d1", "Dataset::kafka::orders"),
            _asset(
                "d2",
                "Dataset::telemetry.raw",
                additionalProperties={"source": "Kafka"},
            ),
        ],
        "Service::": [
            _asset("sv1", "Service::kafka_broker"),
            _asset("sv2", "Service::shared1"),
            _asset("sv3", "Service::batchjob"),
            _asset("sv4", "Service::worker"),
        ],
        "Route::": [
            _asset("rt1", "Route::shared1"),
            _asset(
                "rt2",
                "Route::edge",
                additionalProperties={"upstream": "kafka_broker:9092"},
            ),
            _asset(
                "rt3",
                "Route::orphan",
                additionalProperties={"upstream": "totally-unknown-host"},
            ),
        ],
        "Monitor::": [
            _asset("m1", "Monitor::shared1"),
            _asset("m2", "Monitor::kafka"),
            _asset("m3", "Monitor::nomatch"),
        ],
        "CI::ServiceNow::": [
            _asset("ci1", "CI::ServiceNow::kafka"),
            _asset("ci2", "CI::ServiceNow::orphan"),
            _asset("ci3", "CI::ServiceNow::shared1"),
        ],
        "Client::": [
            _asset("cl1", "Client::realm::kafka_broker"),
            _asset("cl2", "Client::realm::orphan"),
        ],
        "Repository::": [
            _asset(
                "r1",
                "Repository::org/gitlabthing",
                additionalProperties={"source": "GitLab"},
                displayName="Shared Widget",
            ),
            _asset(
                "r2",
                "Repository::org/githubthing",
                additionalProperties={"source": "GitHub"},
                displayName="Shared Widget",
            ),
            _asset(
                "r3",
                "Repository::org/batchjob",
                additionalProperties={"source": "GitLab"},
                displayName="Batch Job Repo",
            ),
            _asset(
                "r4",
                "Repository::org/worker",
                additionalProperties={"source": "GitLab"},
                displayName="Worker Widget",
            ),
        ],
        "Datasource::": [
            _asset("dsc1", "Datasource::grafana::kafka"),
            _asset("dsc2", "Datasource::grafana::orphan"),
        ],
        "ArchiMate::": [_asset("ea1", "ArchiMate::AppComponentX", displayName="kafka")],
        "FactSheet::": [_asset("ea2", "FactSheet::Y", displayName="worker")],
        "Term::": [
            _asset("t1", "Term::glossary/kafka-cluster", displayName="Kafka Cluster")
        ],
    }


class _Resp:
    def __init__(self, items: list[dict]) -> None:
        self.status_code = 200
        self._items = items


class FakeReconcileApi:
    """No-network fake: serves ``_paginated_search`` by literal searchString
    term, records every write call, and backs ``lineage()``/idempotency off
    the same ``link_data_flow`` calls it records — exactly like the real
    client's lineage graph would reflect a prior write.
    """

    def __init__(self, catalog=None, enable_write=True, governance=None):
        self.enable_write = enable_write
        self._catalog = catalog if catalog is not None else _build_catalog()
        self._lineage: dict[str, set[str]] = {}
        self.link_calls: list[tuple[str, str, str]] = []
        self._collections: dict[str, str] = {}
        self.create_collection_calls: list[str] = []
        self._governance: dict[str, dict] = dict(governance or {})
        self.set_confidentiality_calls: list[tuple[str, int]] = []
        self._last_term: str | None = None

    def _bearer(self) -> str:
        return "tok"

    def _omvs(self, service: str, sub_path: str) -> str:
        return f"https://fake.invalid/{service}/{sub_path}"

    def _http(self):
        return self

    def post(self, url, headers=None, content=None):
        body = _json.loads(content)
        self._last_term = body["searchString"]
        return _Resp(self._catalog.get(self._last_term, []))

    def _elements(self, resp: _Resp) -> list[dict]:
        return resp._items

    def lineage(self, guid: str, direction: str = "both", depth: int = 2) -> dict:
        edges = self._lineage.get(guid, set())
        return {
            "lineageLinkage": [
                {"relatedElement": {"elementHeader": {"guid": g}}} for g in edges
            ]
        }

    def link_data_flow(self, source_guid: str, target_guid: str, label: str = ""):
        self.link_calls.append((source_guid, target_guid, label))
        self._lineage.setdefault(source_guid, set()).add(target_guid)
        return {"guid": f"edge-{len(self.link_calls)}"}

    def create_collection(self, name: str, description: str = "", category: str = ""):
        self.create_collection_calls.append(name)
        if name not in self._collections:
            self._collections[name] = f"col-{len(self._collections) + 1}"
        return {"guid": self._collections[name]}

    def governance_for(self, guid: str) -> dict:
        return self._governance.get(guid, {})

    def set_confidentiality(self, guid: str, level: int):
        self.set_confidentiality_calls.append((guid, level))
        self._governance.setdefault(guid, {})["confidentialityLevel"] = level
        return {"ok": True}


_GOVERNANCE = {
    "s1": {"confidentialityLevel": 1},
    "d1": {"confidentialityLevel": 3},
    "d2": {"confidentialityLevel": 5},
}


def _fresh_governance() -> dict[str, dict]:
    # Deep-enough copy: FakeReconcileApi.set_confidentiality mutates the
    # per-guid dict in place, so a shallow `dict(_GOVERNANCE)` would leak
    # mutations across tests via the shared inner dict objects.
    return {guid: dict(levels) for guid, levels in _GOVERNANCE.items()}


def _run() -> tuple[dict, FakeReconcileApi]:
    api = FakeReconcileApi(governance=_fresh_governance())
    return reconcile(api), api


# ── write gate ─────────────────────────────────────────────────────────────
def test_reconcile_write_disabled_returns_error_without_loading_anything():
    class NoWrite:
        enable_write = False

    assert reconcile(NoWrite()) == {
        "error": "writes disabled — set EGERIA_ENABLE_WRITE=true"
    }


# ── full-scan characterization: exact per-pattern link counts ──────────────
def test_reconcile_loaded_counts():
    report, _api = _run()
    assert report["loaded"] == {
        "nodes": 3,
        "stores": 3,
        "datasets": 2,
        "services": 4,
        "routes": 3,
        "monitors": 3,
        "cis": 3,
        "clients": 2,
        "repos": 4,
        "datasources": 2,
        "ea": 2,
    }


def test_reconcile_per_pattern_link_counts_and_total():
    report, _api = _run()
    assert report["summary"] == {
        "host-hosting": 2,
        "service-store": 2,
        "dataset-store": 1,
        "source-store": 1,
        "ingress-exposure": 1,
        "monitoring": 2,
        "cmdb-identity": 2,
        "access-control": 1,
        "repo-service": 2,
        "datasource-store": 1,
        "ea-realization": 2,
        "semantic-assignment": 1,
        "capability-cohort": 6,
        "cross-vendor-identity": 1,
        "confidentiality-propagation": 1,
        "total_links": 26,
    }


def test_reconcile_host_hosting_links_both_node_and_host_prefixed_nodes():
    report, _ = _run()
    assert report["host-hosting"]["items"] == [
        "Node::web1 →[hosts] DataStore::kafka",
        "Host::dbhost →[hosts] DataStore::files",
    ]


def test_reconcile_service_store_matches_by_underscore_split():
    report, _ = _run()
    assert report["service-store"]["items"] == [
        "Service::kafka_broker →[realizes] DataStore::kafka",
        "Service::shared1 →[realizes] DataStore::shared1",
    ]


def test_reconcile_dataset_store_requires_dataset_prefix_naming_convention():
    report, _ = _run()
    # d1's qualifiedName ("Dataset::kafka::orders") matches the naming
    # convention this pattern keys off; d2 ("Dataset::telemetry.raw", one
    # "::") does not, even though it IS hosted by the kafka store per
    # source-store below.
    assert report["dataset-store"]["items"] == [
        "DataStore::kafka →[hosts] Dataset::kafka::orders"
    ]


def test_reconcile_source_store_links_by_additionalProperties_source():
    report, _ = _run()
    assert report["source-store"]["items"] == [
        "DataStore::kafka →[hosts] Dataset::telemetry.raw"
    ]


def test_reconcile_ingress_exposure_parses_upstream_host():
    report, _ = _run()
    assert report["ingress-exposure"]["items"] == [
        "Route::edge →[routes-to] Service::kafka_broker"
    ]


def test_reconcile_access_control_matches_client_id_suffix():
    report, _ = _run()
    assert report["access-control"]["items"] == [
        "Client::realm::kafka_broker →[secures] Service::kafka_broker"
    ]


def test_reconcile_repo_service_matches_repo_basename_to_service():
    report, _ = _run()
    assert report["repo-service"]["items"] == [
        "Repository::org/batchjob →[deploys] Service::batchjob",
        "Repository::org/worker →[deploys] Service::worker",
    ]


def test_reconcile_datasource_store_matches_by_trailing_name():
    report, _ = _run()
    assert report["datasource-store"]["items"] == [
        "Datasource::grafana::kafka →[reads] DataStore::kafka"
    ]


def test_reconcile_semantic_assignment_links_matching_display_name_to_term():
    report, _ = _run()
    assert report["semantic-assignment"]["items"] == [
        "DataStore::kafka →[means] Term::glossary/kafka-cluster"
    ]


def test_reconcile_capability_cohort_requires_two_distinct_sources():
    report, _ = _run()
    # vcs: 4 repos (GitLab x3, GitHub x1) -> 2 distinct sources -> cohort built.
    # enterprise-architecture: ArchiMate + FactSheet -> 2 distinct sources -> cohort built.
    assert report["capability-cohort"]["items"] == [
        "Capability::vcs →[groups] Repository::org/gitlabthing",
        "Capability::vcs →[groups] Repository::org/githubthing",
        "Capability::vcs →[groups] Repository::org/batchjob",
        "Capability::vcs →[groups] Repository::org/worker",
        "Capability::enterprise-architecture →[groups] ArchiMate::AppComponentX",
        "Capability::enterprise-architecture →[groups] FactSheet::Y",
    ]


def test_reconcile_cross_vendor_identity_links_same_display_name_diff_source():
    report, _ = _run()
    assert report["cross-vendor-identity"]["items"] == [
        "Repository::org/gitlabthing →[same-as] Repository::org/githubthing"
    ]


def test_reconcile_confidentiality_propagation_raises_store_to_dataset_level():
    report, api = _run()
    assert report["confidentiality-propagation"]["items"] == [
        "DataStore::kafka → level 3 (from Dataset::kafka::orders)"
    ]
    assert api.set_confidentiality_calls == [("s1", 3)]


def test_reconcile_propagate_confidentiality_false_skips_the_pattern():
    api = FakeReconcileApi(
        governance={"s1": {"confidentialityLevel": 1}, "d1": {"confidentialityLevel": 3}}
    )
    report = reconcile(api, propagate_confidentiality=False)
    assert report["summary"]["confidentiality-propagation"] == 0
    assert api.set_confidentiality_calls == []


def test_reconcile_negative_cases_produce_no_links():
    """m3/nomatch, ci2/orphan, cl2/orphan, rt3/orphan, dsc2/orphan never
    appear as the source of ANY recorded link_data_flow call."""
    _report, api = _run()
    orphan_guids = {"m3", "ci2", "cl2", "rt3", "dsc2"}
    sources_used = {sg for sg, _tg, _label in api.link_calls}
    assert not (orphan_guids & sources_used)


def test_reconcile_rerun_is_idempotent_no_duplicate_links():
    api = FakeReconcileApi(governance=_fresh_governance())
    first = reconcile(api)
    second = reconcile(api)
    assert first["summary"]["total_links"] == 26
    assert second["summary"]["total_links"] == 0
    assert second["summary"]["confidentiality-propagation"] == 0
    # capability-cohort's collection lookup is itself idempotent (same name ->
    # same guid), so the cohort's own group-links are idempotent too.
    assert api.create_collection_calls == [
        "Capability vcs",
        "Capability enterprise-architecture",
        "Capability vcs",
        "Capability enterprise-architecture",
    ]


# ── BUGS FOUND — see plans/complex/lane-reports/CXA-FL-EGERIAMCP-01.md ─────
def test_bug_monitoring_precedence_last_writer_wins_route_over_store_svc_node():
    """BUG-1 (part a): three DIFFERENT asset kinds share the core name
    "shared1" (DataStore::shared1 / Service::shared1 / Node::shared1 /
    Route::shared1). ``_pattern_monitoring``'s ``targets_by_name`` is built by
    ``**``-merging ``store_by_name``, ``svc_by_name``, a Node:: index, and a
    Route:: index IN THAT ORDER — a plain dict update, so the LAST dict
    merged silently wins any name collision with no signal that a collision
    even occurred. Monitor::shared1 ends up wired to the ROUTE, not the
    store/service/node that likely hosts the thing actually being monitored.
    """
    report, api = _run()
    m1_targets = [tg for sg, tg, _label in api.link_calls if sg == "m1"]
    assert m1_targets == ["rt1"]  # Route::shared1 — NOT s2 (store) or sv2 (service) or n3 (node)


def test_bug_cmdb_identity_precedence_disagrees_with_monitoring_for_same_collision():
    """BUG-1 (part b): the SAME "shared1" collision resolves to a DIFFERENT
    winner in ``_pattern_cmdb_identity`` (merge order store -> node -> svc,
    svc wins) than in ``_pattern_monitoring`` (merge order store -> svc ->
    node -> route, route wins) — proving the "winner" is an accident of each
    block's copy-pasted merge-literal order, not a deliberate priority rule.
    """
    report, api = _run()
    ci3_targets = [tg for sg, tg, _label in api.link_calls if sg == "ci3"]
    assert ci3_targets == ["sv2"]  # Service::shared1 — a DIFFERENT winner than monitoring's route


def test_bug_ea_realization_precedence_repo_silently_overwrites_service():
    """BUG-1 (part c): the same defect class in ``_pattern_ea_realization``'s
    ``real_by_name`` (built via services.update() -> stores.update() ->
    repos.update(); Service::worker and Repository::org/worker share core
    name "worker") — the LAST ``.update()`` (repos) wins, so
    FactSheet::Y (displayName "worker") realizes the REPOSITORY, not the
    service most likely intended by an EA element named after a running
    workload.
    """
    report, api = _run()
    ea2_targets = [tg for sg, tg, _label in api.link_calls if sg == "ea2"]
    assert ea2_targets == ["r4"]  # Repository::org/worker — NOT sv4 (Service::worker)


def test_bug_confidentiality_propagation_blind_to_source_store_hosting_edges():
    """BUG-2: ``_pattern_confidentiality_propagation`` (P10) re-derives its own
    "which store hosts this dataset" answer purely from the dataset's
    qualifiedName (``Dataset::<store>::...``) — the SAME rule as P4
    (dataset-store) — instead of consulting the "hosts" edges P4 AND P11
    (source-store) actually created. Dataset::telemetry.raw (d2,
    confidentialityLevel=5) IS hosted by DataStore::kafka per the
    source-store pattern (see source-store link above), but its
    qualifiedName has only one "::" so P10 never even considers it: the
    store ends up raised only to level 3 (from d1), never to 5, silently
    violating the module docstring's own claim ("a store that hosts
    Confidential data is raised to at least that level").
    """
    report, api = _run()
    assert api.set_confidentiality_calls == [("s1", 3)]  # never (s1, 5)
    assert report["confidentiality-propagation"]["links"] == 1  # d2 never counted
